name: Skiko Sample
options:
  bundleIdPrefix: org.jetbrains
settings:
  DEVELOPMENT_TEAM: N462MKSJ7M
  CODE_SIGN_IDENTITY: "Apple Development"
  CODE_SIGN_STYLE: Automatic
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "4"
  SDKROOT: iphoneos
targets:
  Skiko Sample iOS:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    prebuildScripts:
      - script: cd "$SRCROOT" && ./gradlew -p . packForXCode
        name: GradleCompile
    info:
      path: plists/Ios/Info.plist
      properties:
        UILaunchStoryboardName: ""
    sources:
      - path: "src/"
        excludes:
          - "android*/**"
          - "awt*/**"
          - "iosApp*/**"
          - "js*/**"
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      ENABLE_BITCODE: "YES"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"
  Skiko Sample tvOS:
    type: application
    platform: tvOS
    deploymentTarget: "14.0"
    prebuildScripts:
      - script: cd "$SRCROOT" && ./gradlew -p . packForXCode
        name: GradleCompile
    info:
      path: plists/tvOS/Info.plist
      properties:
        UILaunchStoryboardName: ""
    sources:
      - path: "src/"
        excludes:
          - "android*/**"
          - "awt*/**"
          - "iosApp*/**"
          - "js*/**"
    settings:
      LIBRARY_SEARCH_PATHS: "$(inherited)"
      ENABLE_BITCODE: "YES"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"
    
